# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RACSample' do
  use_frameworks!
  # Pods for RACSample
  pod 'ReactiveCocoa'
  pod 'AFNetworking'
  pod 'YYModel'
  pod 'FMDB'

  target 'RACSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RACSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
